name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Python Installation
        run: python3 --version

      - name: Install Dependencies
        run: pip3 install -r PythonApp/requirements.txt

      - name: Execute Python Application
        run: python3 PythonApp/app.py
